# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sinkzone < Formula
  desc "A strict DNS filter to help you stay focused — or keep your kids safe"
  homepage "https://github.com/berbyte/sinkzone"
  version "0.0.57"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.57/sinkzone-darwin-amd64"
      sha256 "fdff1d4a954d38282ea9ee587db77e693a417ed820edc6ac7925bb6a5399531e"

      def install
        bin.install "sinkzone-darwin-amd64" => "sinkzone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.57/sinkzone-darwin-arm64"
      sha256 "db878687d4a69139e55489f0f6d0fa32a81ab1d9a4cd55a9a32e638e6856c727"

      def install
        bin.install "sinkzone-darwin-arm64" => "sinkzone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.57/sinkzone-linux-amd64"
      sha256 "f53718074ea45d6608f1137b6f4333b7c1c5fb795f9007473f89ca6b2dbcb9f8"
      def install
        bin.install "sinkzone-linux-amd64" => "sinkzone"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.57/sinkzone-linux-arm64"
      sha256 "6c5252a6a869c1a41f450a7d5dcd7b44906cfe53abc7209c21566e9ec1d4dcbd"
      def install
        bin.install "sinkzone-linux-arm64" => "sinkzone"
      end
    end
  end
end
