# This file was generated by GoReleaser. DO NOT EDIT.
cask "sinkzone" do
  desc "A strict DNS filter to help you stay focused — or keep your kids safe"
  homepage "https://github.com/berbyte/sinkzone"
  version "0.0.25"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sinkzone"

  on_macos do
    on_intel do
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.25/sinkzone_Darwin_x86_64.tar.gz"
      sha256 "d69c35a632d73203625615b4b8724b68455c4ff25471dd6cb3dff02730ccc582"
    end
    on_arm do
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.25/sinkzone_Darwin_arm64.tar.gz"
      sha256 "1028d9781b2b990b1a95a95053d82c286470c2a3a9f4efc0d45fad2e040bb82f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.25/sinkzone_Linux_x86_64.tar.gz"
      sha256 "3c794e36869529e38d9b1de951570d05fd8ac0a844844d528ecb4dd5db6bf59a"
    end
    on_arm do
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.25/sinkzone_Linux_arm64.tar.gz"
      sha256 "4583c5ff7830bb5e9d8fcf0611dcf73f052e68f9b802a5dfc47cf03b598dec0a"
    end
  end

  # No zap stanza required
end
